'use client';
// components/screens/ReportScreen.tsx

import { useApp } from '@/lib/store';
import { emergencyData } from '@/lib/emergencyData';
import FlowStrip from '@/components/ui/FlowStrip';
import styles from './ReportScreen.module.css';

type StepStatus = 'done' | 'progress' | string;
type PatientStatus = 'yes' | 'no' | string;
type EmergencyKey = keyof typeof emergencyData;

interface EmergencyStep {
  title: string;
}

interface EmergencyDataItem {
  label: string;
  severity: string;
  sevTitle: string;
  doctorRec: string;
  steps: EmergencyStep[];
}

interface UseAppState {
  selected: EmergencyKey | null;
  description: string;
  stepStatuses: Record<number, StepStatus>;
  patientStatus: PatientStatus;
  reportTime: string;
  resetAll: () => void;
}

export default function ReportScreen() {
  const { selected, description, stepStatuses, patientStatus, reportTime, resetAll } = useApp() as UseAppState;
  if (!selected) return null;

  const data: EmergencyDataItem = emergencyData[selected];

  const downloadReport = () => {
    const content = [
      'MEDIASSIST EMERGENCY REPORT',
      '='.repeat(40),
      `Generated: ${reportTime}`,
      `Emergency: ${data.label}`,
      `Severity: ${data.severity}`,
      '',
      'Patient Description:',
      description || 'Emergency situation described.',
      '',
      'First Aid Steps:',
      ...data.steps.map((s, i) =>
        `${i + 1}. ${s.title} — ${stepStatuses[i] === 'done' ? 'COMPLETED' : stepStatuses[i] === 'progress' ? 'IN PROGRESS' : 'Pending'}`
      ),
      '',
      'AI Recommendation:',
      data.doctorRec,
      '',
      `Patient Status: ${patientStatus === 'yes' ? 'Improving' : 'Not improving / Escalated to 112'}`,
      '',
      'Powered by MediAssist AI',
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `mediassist-report-${Date.now()}.txt`;
    a.click();
  };

  return (
    <section className={styles.report}>
      <div style={{ width: '100%', maxWidth: 750, display: 'flex', justifyContent: 'center' }}>
        <FlowStrip current="report" />
      </div>

      {/* Header */}
      <div className={styles.header}>
        <div className={styles.headerDecor} />
        <h2>Medical Report</h2>
        <p>Generated by MediAssist AI — Share this with your doctor</p>
        <div className={styles.meta}>
          <span>📅 {reportTime}</span>
          <span>🚨 {data.label}</span>
          <span>⚡ {data.severity.charAt(0).toUpperCase() + data.severity.slice(1)}</span>
        </div>
      </div>

      {/* Summary */}
      <div className={styles.section}>
        <h3>Incident Summary</h3>
        <div className={styles.row}>
          <span className={styles.label}>Emergency Type</span>
          <span className={styles.value}>{data.label}</span>
        </div>
        <div className={styles.row}>
          <span className={styles.label}>Symptoms Described</span>
          <span className={styles.value}>{description || 'Emergency situation described.'}</span>
        </div>
        <div className={styles.row}>
          <span className={styles.label}>AI Severity Assessment</span>
          <span className={styles.value}>{data.sevTitle}</span>
        </div>
        <div className={styles.row}>
          <span className={styles.label}>Patient Status</span>
          <span className={styles.value}>
            {patientStatus === 'yes'
              ? '✅ Improving after first aid'
              : patientStatus === 'no'
              ? '⚠️ Not improving — escalated to 112'
              : '⏳ Under observation'}
          </span>
        </div>
      </div>

      {/* Steps */}
      <div className={styles.section}>
        <h3>First Aid Steps Followed</h3>
        <ul className={styles.stepsList}>
          {data.steps.map((step, i) => {
            const done = stepStatuses[i] === 'done';
            const progress = stepStatuses[i] === 'progress';
            return (
              <li key={i} className={styles.stepsItem}>
                <div className={`${styles.checkIcon} ${done ? styles.checkDone : progress ? styles.checkProg : ''}`}>
                  ✓
                </div>
                <span>
                  {step.title}
                  {!done && !progress && (
                    <span className={styles.pending}> (pending)</span>
                  )}
                  {progress && (
                    <span className={styles.inprog}> (in progress)</span>
                  )}
                </span>
              </li>
            );
          })}
        </ul>
      </div>

      {/* Doctor Rec */}
      <div className={styles.section}>
        <h3>AI Recommendation for Doctor</h3>
        <p className={styles.rec}>{data.doctorRec}</p>
      </div>

      {/* Actions */}
      <div className={styles.actions}>
        <button className={styles.downloadBtn} onClick={downloadReport}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3" />
          </svg>
          Download Report
        </button>
        <button className={styles.newBtn} onClick={resetAll}>
          New Emergency
        </button>
      </div>
    </section>
  );
}