'use client';
import { useApp } from '@/lib/store';
import { emergencyData } from '@/lib/emergencyData';
import styles from './ReportScreen.module.css';

export default function ReportScreen() {
  const { selected, description, stepHistory, patientStatus, reportTime, resetAll } = useApp();
  if (!selected) return null;
  const data = emergencyData[selected];

  const download = () => {
    const lines = [
      'MEDIASSIST EMERGENCY REPORT',
      '='.repeat(38),
      `Date: ${reportTime}`,
      `Emergency: ${data.label}`,
      `Severity: ${data.sevLabel}`,
      '',
      'Situation described:',
      description || 'No description provided.',
      '',
      'Steps followed:',
      ...stepHistory.map((s, i) => `${i + 1}. ${s}`),
      '',
      `Patient status: ${patientStatus === 'yes' ? 'Improving' : patientStatus === 'no' ? 'Not improving — 112 called' : 'Unknown'}`,
      '',
      'For the doctor:',
      data.doctorRec,
      '',
      'Generated by MediAssist',
    ].join('\n');

    const a = document.createElement('a');
    a.href = URL.createObjectURL(new Blob([lines], { type: 'text/plain' }));
    a.download = `mediassist-${selected}-${Date.now()}.txt`;
    a.click();
  };

  return (
    <main className={styles.page}>
      {/* Header */}
      <div className={`${styles.header} animate-up`}>
        <div className={styles.headerEmoji}>{data.emoji}</div>
        <div>
          <div className={styles.headerLabel}>Emergency Report</div>
          <h2 className={styles.headerTitle}>{data.label}</h2>
          {reportTime && <div className={styles.headerTime}>{reportTime}</div>}
        </div>
      </div>

      {/* Status */}
      <div className={`${styles.statusCard} animate-up d1 ${patientStatus === 'yes' ? styles.statusGood : styles.statusBad}`}>
        <span>{patientStatus === 'yes' ? '✅' : patientStatus === 'no' ? '🚨' : '⏳'}</span>
        <span>
          {patientStatus === 'yes' ? 'Patient improving after first aid'
           : patientStatus === 'no' ? 'Not improving — emergency services called'
           : 'Status not recorded'}
        </span>
      </div>

      {/* Situation */}
      <div className={`${styles.section} animate-up d2`}>
        <div className={styles.sectionLabel}>What happened</div>
        <p className={styles.sectionText}>{description || 'No description recorded.'}</p>
      </div>

      {/* Steps */}
      {stepHistory.length > 0 && (
        <div className={`${styles.section} animate-up d3`}>
          <div className={styles.sectionLabel}>Steps completed ({stepHistory.length})</div>
          <div className={styles.stepsList}>
            {stepHistory.map((s, i) => (
              <div key={i} className={styles.stepRow}>
                <div className={styles.stepNum}>{i + 1}</div>
                <span>{s}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Doctor note */}
      <div className={`${styles.section} ${styles.doctorSection} animate-up d4`}>
        <div className={styles.sectionLabel}>📋 Note for the doctor</div>
        <p className={styles.sectionText}>{data.doctorRec}</p>
      </div>

      {/* Actions */}
      <div className={`${styles.actions} animate-up d5`}>
        <button className={styles.downloadBtn} onClick={download}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/>
          </svg>
          Save report
        </button>
        <button className={styles.homeBtn} onClick={resetAll}>New emergency</button>
      </div>
    </main>
  );
}